export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_ERROR = 'FETCH_RECIPES_ERROR';

export const ADD_TO_RECIPES = 'ADD_TO_RECIPES';
export const REMOVE_FROM_RECIPES = 'REMOVE_FROM_RECIPES';