export const FETCH_USER_RECIPES_REQUEST = 'FETCH_USER_RECIPES_REQUEST';
export const FETCH_USER_RECIPES_SUCCESS = 'FETCH_USER_RECIPES_SUCCESS';
export const FETCH_USER_RECIPES_ERROR = 'FETCH_USER_RECIPES_ERROR';

export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';

export const REMOVE_RECIPE = 'REMOVE_RECIPE';
